# Generated by Django 5.2 on 2025-09-15 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0014_cuerpodocumentoitem_precioindiceusado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Sucursal')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código de Sucursal')),
                ('codEstableMH', models.CharField(max_length=4, verbose_name='Código Establecimiento MH')),
                ('codEstable', models.CharField(max_length=4, verbose_name='Código Establecimiento')),
                ('codPuntoVentaMH', models.CharField(max_length=4, verbose_name='Código Punto Venta MH')),
                ('codPuntoVenta', models.CharField(max_length=15, verbose_name='Código Punto Venta')),
                ('activa', models.BooleanField(default=True, verbose_name='Sucursal Activa')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'db_table': 'dte_sucursal',
            },
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='sucursal',
            field=models.ForeignKey(blank=True, help_text='Sucursal que emite la factura', null=True, on_delete=django.db.models.deletion.PROTECT, to='dte.sucursal', verbose_name='Sucursal'),
        ),
    ]
