# Generated by Django 5.2 on 2025-09-15 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0015_sucursal_facturaelectronica_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaelectronica',
            name='sucursal',
            field=models.ForeignKey(default=1, help_text='Sucursal que emite la factura', on_delete=django.db.models.deletion.PROTECT, to='dte.sucursal', verbose_name='Sucursal'),
            preserve_default=False,
        ),
    ]
