# Generated by Django 5.2 on 2025-09-15 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0015_sucursal_facturaelectronica_sucursal'),
        ('productos', '0006_usuario_activo_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='sucursal',
            field=models.ForeignKey(blank=True, help_text='Sucursal a la que pertenece el usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dte.sucursal', verbose_name='Sucursal Asignada'),
        ),
    ]
